const scienceCases=[["Bitkinin ışıkta büyümesini karşılaştıran Ece","Gözlem yapıp sonuçları kaydetmek","Merak ve dikkat"],["Mıknatısın hangi maddeleri çektiğini araştıran Arda","Nesneleri güvenle deneyip bulguları yazmak","Araştırmacılık"],["Gölgenin gün içindeki değişimini izleyen Mina","Aynı yerde farklı saatlerde ölçüm yapmak","Sabır"],["Tohumların filizlenme süresini inceleyen Can","Koşulları eşit tutup gözlem yapmak","Düzenlilik"],["Yağmur miktarını ölçen Deniz","Ölçümleri tarihleriyle kaydetmek","Titizlik"],["Suyun kaldırma kuvvetini merak eden Ela","Tahmin kurup güvenli deney yapmak","Merak"],["Hayvanları doğal ortamında inceleyen Kerem","Canlılara zarar vermeden gözlemlemek","Sorumluluk"],["Gökyüzündeki Ay'ı izleyen Zeynep","Gözlemleri çizelgeye aktarmak","Dikkat"],["Temiz su çözümü arayan Selin","İnsanların ihtiyacına yararlı çözüm geliştirmek","Yardımseverlik"],["Enerji tasarrufu yöntemi araştıran Mert","Kanıtları karşılaştırıp uygun öneri sunmak","Sorgulama"],["Deneyi ilk seferde sonuçlanmayan Ali","Yöntemini gözden geçirip yeniden denemek","Azim"],["Farklı kaynaklarda bilgi arayan Duru","Güvenilir kaynakları karşılaştırmak","Eleştirel düşünme"],["Bir hastalığın nedenini araştıran bilim insanı","Gözlem ve kanıtlardan yararlanmak","Özen"],["Yeni bir ölçme aracı tasarlayan Bora","Aracı deneyip eksiklerini geliştirmek","Yaratıcılık"],["Takımıyla deney yapan Naz","Görev paylaşarak birlikte çalışmak","İş birliği"],["Laboratuvarda çalışan Ayşe","Koruyucu araç kullanıp kurallara uymak","Güvenlik bilinci"],["Sonucunu sınıfa sunan Eren","Bulguları açık ve doğru biçimde paylaşmak","Dürüstlük"],["Bir tahminin doğru olup olmadığını araştıran İpek","Tahmini deney ve gözlemle sınamak","Kanıta dayanma"],["Çevre kirliliğine çözüm arayan Ömer","Sorunu inceleyip uygulanabilir çözüm üretmek","Çevre duyarlılığı"],["Kuşların göçünü araştıran Aslı","Uzun süreli gözlem sonuçlarını karşılaştırmak","Sabır"],["Bir buluşun etkilerini inceleyen Berk","Yararlarını ve olası zararlarını birlikte düşünmek","Sorumluluk"],["Eski uygarlıklara ait kalıntıları inceleyen arkeolog","Buluntuları koruyup kanıtlarla yorumlamak","Geçmişe saygı"],["Uzayı araştıran astronom","Teleskop gözlemlerini kaydedip karşılaştırmak","Merak"],["Yeni bir ilaç üzerinde çalışan ekip","Çalışmayı güvenlik kurallarıyla ve dikkatle yürütmek","Özen"],["Bilim şenliğine hazırlanan öğrenciler","Sorularını, yöntemlerini ve sonuçlarını paylaşmak","İletişim"]];
const technologyCases=[["Mektuptan görüntülü görüşmeye","İletişim","Kişisel bilgileri paylaşmadan ve süreyi dengeli kullanmak"],["Daktilodan bilgisayara","Yazı yazma","Ekrana uygun uzaklıktan bakıp ara vermek"],["Kâğıt haritadan navigasyona","Yol bulma","Güvenli yerde kullanıp çevreyi de kontrol etmek"],["Mumdan LED lambaya","Aydınlatma","Gereksiz ışıkları kapatmak"],["Çamaşır tahtasından çamaşır makinesine","Temizlik","Bir yetişkinin yardımıyla kullanmak"],["Süpürgeden robot süpürgeye","Ev temizliği","Çalışırken hareketli parçalarına dokunmamak"],["Abaküsten hesap makinesine","Hesaplama","Önce düşünmek, sonucu kontrol için kullanmak"],["Kum saatinden dijital saate","Zamanı ölçme","Zamanı planlı kullanmak"],["Filmli makineden dijital kameraya","Görüntü kaydetme","İzin almadan kimsenin fotoğrafını çekmemek"],["Radyodan çevrim içi yayına","Sesli bilgi ve eğlence","Yaşa uygun içerik seçmek"],["Tüplü televizyondan akıllı televizyona","Görüntülü yayın izleme","Ekran süresini sınırlamak"],["Klasik termometreden dijital termometreye","Sıcaklık ölçme","Sağlık ölçümünde yetişkinden yardım almak"],["Pedallı bisikletten elektrik destekli bisiklete","Ulaşım","Kask takıp trafik kurallarına uymak"],["Kömür enerjisinden güneş paneline","Enerji üretme","Enerjiyi tasarruflu kullanmak"],["Eski su süzme yöntemlerinden su arıtma cihazına","Suyu temizleme","Bakımını zamanında yaptırmak"],["El aletlerinden tarım makinelerine","Tarım işlerini kolaylaştırma","Yalnız eğitimli yetişkinlerin kullanması"],["Stetoskoptan görüntüleme cihazlarına","Sağlığı inceleme","Uzmanların yönergelerine uymak"],["Basit protezlerden gelişmiş protezlere","Hareketi destekleme","Kişinin ihtiyacına uygun kullanmak"],["Kulak borusundan işitme cihazına","İşitmeyi destekleme","Ses düzeyini uzman önerisine göre ayarlamak"],["Posta güvercininden e-postaya","Haberleşme","Tanımadığımız iletilerde bağlantı açmamak"],["Kütüphane fişlerinden dijital kataloğa","Bilgiye ulaşma","Kaynağın güvenilirliğini kontrol etmek"],["Elle açılan kapıdan sensörlü kapıya","Geçişi kolaylaştırma","Sensörleri amacı dışında kullanmamak"],["Trafik polisinin işaretinden akıllı trafik ışığına","Trafiği düzenleme","Işık ve yaya kurallarına uymak"],["El çiziminden tasarım programına","Tasarım yapma","Başkalarının eserini izinsiz kopyalamamak"],["Basit oyuncaktan eğitim robotuna","Kodlama ve problem çözme","Robotu güvenli alanda ve amacına uygun kullanmak"]];
const artCases=[["Resim","Renk ve çizgilerle duygu ve düşünce anlatır","Eseri dikkatle inceleyip farklı yorumlara saygı göstermek"],["Müzik","Ses ve ritimle duygu paylaşır","Başkalarını rahatsız etmeyecek ses düzeyi seçmek"],["Tiyatro","Olayları canlandırarak düşündürür ve eğlendirir","Oyun sırasında sessizce izleyip sonunda alkışlamak"],["Dans","Beden hareketleriyle duygu ve kültür anlatır","Hareket alanına ve arkadaşlara saygı göstermek"],["Heykel","Taş, kil veya başka malzemelerle üç boyutlu eser oluşturur","Müzedeki eserlere dokunmamak"],["Mimari","Yaşam alanlarını işlevli ve estetik biçimde tasarlar","Tarihî yapıları korumak"],["Seramik","Kile biçim ve desen vererek günlük veya süs eşyası üretir","Kırılabilir eseri dikkatle kullanmak"],["Dokuma","İpliklerle desenli kumaş ve kilim oluşturur","El emeğine değer vermek"],["Ebru","Su üzerindeki renklerle özgün desenler oluşturur","Malzemeyi özenli ve tasarruflu kullanmak"],["Hat sanatı","Yazıyı estetik biçimde düzenler","Eseri küçümsemeden incelemek"],["Halk oyunu","Bir yörenin müzik ve hareket kültürünü yaşatır","Farklı yörelerin oyunlarına saygı duymak"],["Fotoğraf","Anları ve çevreyi görüntüyle anlatır","İnsanların fotoğrafını çekmeden izin istemek"],["Sinema","Görüntü, ses ve öyküyü birleştirir","Yaşa uygun film seçmek"],["İllüstrasyon","Bir metni resimlerle anlamayı kolaylaştırır","Çizerin emeğini belirtmek"],["Şiir","Duygu ve düşünceleri ahenkli sözlerle anlatır","Şiiri dikkatle dinlemek"],["Hikâye anlatıcılığı","Olayları sözlerle canlandırıp hayal gücünü geliştirir","Anlatanı sözünü kesmeden dinlemek"],["Kukla","Karakterleri kuklalarla canlandırır","Kuklaları özenle kullanmak"],["Mozaik","Küçük parçaları birleştirerek desen ve resim oluşturur","Tarihî mozaikleri korumak"],["Ahşap oyma","Ahşaba desen ve biçim verir","Kesici araçları yalnız yetişkin gözetiminde kullanmak"],["Çini","Seramik yüzeyleri geleneksel desenlerle süsler","Kültürel motiflere değer vermek"],["El sanatları","Geleneksel bilgi ve el emeğini günlük eşyalara taşır","Üreten kişinin emeğine saygı göstermek"],["Duvar resmi","Ortak alanları renk ve imgelerle güzelleştirir","İzinli yüzeylerde çalışmak"],["Kostüm tasarımı","Karakteri renk, kumaş ve biçimle anlatır","Malzemeleri israf etmeden kullanmak"],["Müze sergisi","Sanat eserlerini bir araya getirip tanıtır","Sergi kurallarına uymak"],["Geri dönüşüm sanatı","Atık malzemeleri yaratıcı eserlere dönüştürür","Temiz ve güvenli malzeme seçmek"]];

const sciencePool=Array.from({length:100},(_,i)=>{
 const x=scienceCases[i%25],t=Math.floor(i/25);
 if(t===0)return [x[0]+" hangi bilimsel davranışı göstermelidir?","🔬",x[1],[x[1],"Sonucu tahminine göre değiştirmek","Kaynak göstermeden paylaşmak","Güvenlik kurallarını önemsememek"]];
 if(t===1)return [x[0]+" için başarıyı destekleyen özellik hangisidir?","🧠",x[2],[x[2],"Dikkatsizlik","Sabırsızlık","Önyargı"]];
 if(t===2)return [x[0]+" çalışmasının topluma ya da bilgiye katkısı nasıl güçlenir?","🌍","Sonuçları kanıtlarla ve anlaşılır biçimde paylaşarak",["Sonuçları kanıtlarla ve anlaşılır biçimde paylaşarak","Yalnız kendi tahminini doğru sayarak","Başka görüşleri dinlemeyerek","Kayıtları silerek"]];
 return [x[0]+" bir sonuç elde ettiğinde bundan sonra ne yapmalıdır?","📋","Sonucu kontrol edip kayıtlarıyla karşılaştırmak",["Sonucu kontrol edip kayıtlarıyla karşılaştırmak","Sonucu kanıtsız biçimde genellemek","İşe yaramayan bilgileri uydurmak","Çalışmayı güvenliksiz sürdürmek"]];
});
const technologyPool=Array.from({length:100},(_,i)=>{
 const x=technologyCases[i%25],t=Math.floor(i/25);
 if(t===0)return ["“"+x[0]+"” değişimi en çok hangi ihtiyaca hizmet eder?","⚙️",x[1],[x[1],"Mevsimleri değiştirme","Uykuyu gereksiz kılma","Bütün işleri insansız yapma"]];
 if(t===1)return ["“"+x[0]+"” örneği bize teknolojinin hangi özelliğini gösterir?","⏳","İhtiyaçlara göre zamanla gelişebildiğini",["İhtiyaçlara göre zamanla gelişebildiğini","Her zaman zararsız olduğunu","Eski araçların hiç işe yaramadığını","İnsanların düşünmesine gerek bırakmadığını"]];
 if(t===2)return ["“"+x[0]+"” teknolojisini kullanırken en doğru davranış hangisidir?","🛡️",x[2],[x[2],"Kuralları önemsememek","Aracı amacı dışında kullanmak","Başkalarının hakkını gözetmemek"]];
 return ["“"+x[0]+"” teknolojisinin yararını değerlendirirken hangisi birlikte düşünülmelidir?","⚖️","Kolaylıkları, güvenlik kuralları ve çevreye etkisi",["Kolaylıkları, güvenlik kuralları ve çevreye etkisi","Yalnız dış görünüşü","Yalnız fiyatının yüksekliği","Hiçbir kural olmadan kullanılması"]];
});
const artPool=Array.from({length:100},(_,i)=>{
 const x=artCases[i%25],t=Math.floor(i/25);
 if(t===0)return [x[0]+" günlük yaşamımıza nasıl katkı sağlar?","🎨",x[1],[x[1],"Bütün insanların aynı şeyi düşünmesini sağlar","Günlük yaşamı sanattan tamamen ayırır","Yalnız sanatçıların duygu hissetmesini sağlar"]];
 if(t===1)return [x[0]+" ile karşılaşınca sanatsever bir çocuk nasıl davranır?","🤝",x[2],[x[2],"Eseri izinsiz değiştirmek","Farklı düşüncelerle alay etmek","Sanatçının emeğini yok saymak"]];
 if(t===2)return [x[0]+" çalışması yapan bir çocuk en çok hangi yönünü geliştirir?","✨","Yaratıcılığını ve kendini ifade etme becerisini",["Yaratıcılığını ve kendini ifade etme becerisini","Başkalarının düşüncesini küçümsemeyi","Her eserin aynı olması gerektiğini","Kuralları görmezden gelmeyi"]];
 return [x[0]+" neden kültürümüz ve ortak yaşamımız için değerlidir?","🏛️","Duygu, düşünce ve kültürel birikimi paylaşmaya yardım ettiği için",["Duygu, düşünce ve kültürel birikimi paylaşmaya yardım ettiği için","Yalnız pahalı olduğu için","Her zaman tek bir anlam taşıdığı için","Günlük yaşamla ilgisi olmadığı için"]];
});

const sections=[
 {code:"HB.2.6.1",color:"#405fc4",soft:"#e9edff",icon:"🔬",title:"İyi ki Bilim İnsanları Var",intro:"Bilim insanlarının merak, gözlem, araştırma, kanıt, azim ve iş birliğiyle yaşamımıza nasıl katkı sunduğunu keşfet.",badge:"Bilim Kâşifi Rozeti",games:[{id:"bilim-insanlari-100",icon:"🔭",title:"Bilim İzinde 100",desc:"Bilimsel süreçleri, bilim insanı özelliklerini ve topluma katkıları değerlendir.",q:sciencePool}]},
 {code:"HB.2.6.2",color:"#0f766e",soft:"#dff8f3",icon:"⚙️",title:"Gelişen Teknoloji",intro:"Teknolojik araçların ihtiyaçlarla birlikte nasıl değiştiğini, yararlarını ve güvenli kullanımını keşfet.",badge:"Teknoloji Bilgesi Rozeti",games:[{id:"teknoloji-100",icon:"🤖",title:"Teknoloji Zaman Yolculuğu",desc:"Eski ve yeni teknolojileri, amaçlarını, etkilerini ve sorumlu kullanımı değerlendir.",q:technologyPool}]},
 {code:"HB.2.6.3",color:"#b45309",soft:"#fff0d8",icon:"🎨",title:"Sanatın Günlük Yaşamımızdaki Yeri",intro:"Sanatın duygu, düşünce, kültür ve çevremizle kurduğu bağı farklı sanat dallarıyla keşfet.",badge:"Sanat Dostu Rozeti",games:[{id:"sanat-100",icon:"🎭",title:"Sanatla Yaşam 100",desc:"Sanat dallarının günlük yaşamdaki yerini ve sanat eserlerine saygılı yaklaşımı değerlendir.",q:artPool}]}
];

let state=JSON.parse(localStorage.getItem("bilim-teknoloji-sanat-progress")||'{"score":0,"wins":{}}');
const worlds=document.getElementById("worlds"),modal=document.getElementById("modal");
let game=null,qi=0,correct=0,locked=false;

function render(){
 worlds.innerHTML=sections.map((s,si)=>`<article class="world" style="--c:${s.color};--soft:${s.soft}">
 <div class="world-head"><div class="world-icon">${s.icon}</div><div><div class="code">${s.code}</div><h2>${si+1}. Bölüm · ${s.title}</h2><div>${s.badge} ${sectionWon(s)?"✅":"🔒"}</div></div></div>
 <div class="intro"><b>Konuyu keşfet</b>${s.intro}</div>
 <div class="cards">${s.games.map(g=>`<button class="card" data-id="${g.id}" style="--c:${s.color}"><span class="emoji">${g.icon}</span><h3>${g.title}</h3><p>${g.desc}</p><strong>${state.wins[g.id]?"Tamamlandı ✓":"Oyunu aç →"}</strong></button>`).join("")}</div></article>`).join("");
 document.querySelectorAll(".card").forEach(b=>b.onclick=()=>start(findGame(b.dataset.id)));
 updateProgress();
}
function findGame(id){for(const s of sections){const g=s.games.find(x=>x.id===id);if(g)return {...g,section:s}}}
function sectionWon(s){return s.games.every(g=>state.wins[g.id])}
function updateProgress(){document.getElementById("stars").textContent=state.score;document.getElementById("badges").textContent=sections.filter(sectionWon).length+"/3"}
function start(g){game={...g,q:[...g.q].sort(()=>Math.random()-.5)};qi=0;correct=0;locked=false;modal.hidden=false;document.body.style.overflow="hidden";showQ()}
function showQ(){
 const q=game.q[qi];locked=false;
 document.getElementById("gameHead").innerHTML=`<div class="game-title">${game.icon} ${game.title}</div><div class="game-meta">${game.section.code} · ${correct*10} puan</div>`;
 document.getElementById("bar").style.width=(qi/game.q.length*100)+"%";
 document.getElementById("question").innerHTML=`<div class="qno">GÖREV ${qi+1} / ${game.q.length}</div><div class="prompt">${q[0]}</div><div class="scene">${q[1]}</div>`;
 const opts=[...q[3]].sort(()=>Math.random()-.5);
 document.getElementById("answers").innerHTML=opts.map(a=>`<button class="answer">${a}</button>`).join("");
 document.getElementById("feedback").textContent="";document.getElementById("next").hidden=true;
 document.querySelectorAll(".answer").forEach(b=>b.onclick=()=>answer(b,q[2]));
}
function answer(btn,right){if(locked)return;locked=true;document.querySelectorAll(".answer").forEach(b=>{b.disabled=true;if(b.textContent===String(right))b.classList.add("good")});if(btn.textContent===String(right)){correct++;btn.classList.add("good");document.getElementById("feedback").textContent="Harika! Doğru cevap. +10 puan ⭐"}else{btn.classList.add("bad");document.getElementById("feedback").textContent="Birlikte öğrendik! Doğru cevap: "+right}document.getElementById("next").hidden=false}
document.getElementById("next").onclick=()=>{qi++;if(qi<game.q.length)showQ();else finish()};
function finish(){const won=correct>=80;if(won&&!state.wins[game.id]){state.wins[game.id]=true;state.score+=correct*10}else if(!state.wins[game.id])state.score+=correct*10;localStorage.setItem("bilim-teknoloji-sanat-progress",JSON.stringify(state));document.getElementById("bar").style.width="100%";document.getElementById("question").innerHTML=`<div class="result"><div class="cup">${won?"🏆":"🌱"}</div><h2>${won?"Görev tamamlandı!":"Bir kez daha deneyelim!"}</h2><p>100 sorudan ${correct} tanesini doğru cevapladın. ${won?"Bu oyunun yıldızını kazandın!":"80 doğruya ulaştığında oyunu tamamlayacaksın."}</p><button class="play-again" id="again">${won?"Oyunlara dön":"Yeniden oyna"}</button></div>`;document.getElementById("answers").innerHTML="";document.getElementById("feedback").textContent="";document.getElementById("next").hidden=true;document.getElementById("again").onclick=()=>won?closeGame():start(game);render()}
function closeGame(){modal.hidden=true;document.body.style.overflow="";render()}
document.getElementById("close").onclick=closeGame;modal.onclick=e=>{if(e.target===modal)closeGame()};
document.getElementById("reset").onclick=()=>{if(confirm("Tüm puan ve rozetler sıfırlansın mı?")){state={score:0,wins:{}};localStorage.setItem("bilim-teknoloji-sanat-progress",JSON.stringify(state));render()}};
render();